---
abstract: 'OAuth for your Dancer2 app'
author:
  - 'Menno Blom <blom@cpan.org>'
build_requires:
  Plack::Test: '0'
  Test::Mock::LWP::Dispatch: '0'
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.038'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-Auth-OAuth
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dancer2: '0.150000'
  DateTime: '0'
  Digest::MD5: '0'
  File::Slurp: '0'
  JSON::Any: '0'
  Module::Load: '0'
  Net::OAuth: '0'
  Scalar::Util: '0'
  URI::Query: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/b10m/p5-Dancer2-Plugin-Auth-OAuth/issues
  homepage: https://github.com/b10m/p5-Dancer2-Plugin-Auth-OAuth
  repository: https://github.com/b10m/p5-Dancer2-Plugin-Auth-OAuth.git
version: '0.01'
x_contributors:
  - 'B10m <menno@b10m.net>'
